openapi: 3.0.1
info:
  title: Documentacion de Api
  description: Documentacion de la API
  version: 1.0.0
tags:
  - name: Products
paths:
  /api/products:
    get:
      summary: Obtiene todos los productos
      description: Retorna todos los productos disponibles
      tags:
        - Products
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
              message: Operación exitosa
        '500':
          description: Error interno del servidor
  /api/products/{pid}:
    get:
      summary: Obtiene los datos de un producto por ID
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto solicitado
          schema:
            type: string
      responses:
        '200':
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
        '500':
          description: Error interno del servidor
components:
  schemas:
    Products:
      type: object
      properties:
        // Propiedades del producto aquí